resource "local_file" "pet" {
  filename = var.filename
  content = "My Fav pet is ${random_pet.my-pet.id}"
}
resource "random_pet" "my-pet" {
    prefix = var.prefix
    separator = var.separator
    length = var.length
}
output "my_output" {
    value = random_pet.my-pet.id
    description = "This will desplay the pet ID generated by random_pet"
}